version: '3'

services:
  app:
    container_name: cliff_app
    build: .
    ports:
      - 8080:8080
    networks:
      - common
    depends_on:
      - redis
  redis:
    image: redis:7.2.1-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - common

networks:
  common:
   driver: bridge
volumes:
  redis_data:
