version: '3'

services:
  app:
    container_name: cliff_app
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - common
    depends_on:
      - redis
  redis:
    image: redis:7.2.1-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - common
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    networks:
      - common
networks:
  common:
   driver: bridge
volumes:
  redis_data:
