apiVersion: v1
kind: Service
metadata:
  name: link-shortener-service
spec:
  selector:
    app: link-shortener
  ports:
    - protocol: TCP
      port: 30800
      targetPort: 8080
  type: NodePort
  